project:
  type: website

metadata-files: 
  - docs/blog/posts/_sidebar.yml

website:
  title: "Home"
  search: True
  site-url: https://ui-seok.github.io/
  site-path: '/'
  page-footer: "us.lee1520@gmail.com"
  repo-url: https://github.com/Ui-Seok/Ui-Seok.github.io
  repo-actions: [edit]
  navbar:
    left:
      - href: about.qmd
        text: Contact Me
      - docs/coursera/index.qmd
      - docs/blog/index.qmd

    right:
      - icon: github
        href: https://github.com/Ui-Seok
      - icon: twitter
        href: https://twitter.com
      - icon: linkedin
        href: https://www.linkedin.com/in/uiseok-lee-34007429a/

format:
  html:
    theme: cosmo
    css: styles.css

